In [1]:
import numpy as np
import math

In [2]:
## Problem 4

In [3]:
f=open('P4_data.txt','rb')

In [4]:
data=[]
for line in f:
    cols=line.strip().split('\t')
    data.append(np.array((float(cols[1]),float(cols[2]))))
f.close()

In [5]:
data

[array([ 1. ,  2.5]),
 array([ 2.,  3.]),
 array([ 3.,  1.]),
 array([ 3.,  2.]),
 array([ 3.5,  2. ])]

In [6]:
f=open('P4_step1.txt','wb')

for i in range(len(data)):
    for j in range(len(data)):
        dist = float("{0:.2f}".format(math.sqrt((data[i][0]-data[j][0])**2+(data[i][1]-data[j][1])**2)))
        f.write(str(dist)+'\t')
    f.write('\n')

In [7]:
f.close()

In [8]:
## Problem 3

In [9]:
f=open('P3_data.txt','rb')

In [10]:
data=[]
for line in f:
    cols=line.strip().split('\t')
    data.append(np.array((float(cols[1]),float(cols[2]))))
f.close()

In [11]:
f=open('P3_step1.txt','wb')

C=[np.array((0,0)),np.array((2,3)),np.array((1.5,-1))]

for i in range(len(data)):
    r=[]
    for j in range(len(C)):
        dist = float("{0:.2f}".format(math.sqrt((data[i][0]-C[j][0])**2+(data[i][1]-C[j][1])**2)))
        r.append(dist)
        f.write(str(dist)+'\t')
    f.write(str(r.index(min(r))+1))
    f.write('\n')
f.close()

In [12]:
def CoG(points):
    x=0
    y=0
    for i in range(len(points)):
        x += points[i][0]
        y += points[i][1]
    return np.array((x/len(points), y/len(points)))

In [13]:
newC1=[]

In [14]:
assign1 = [1,6,7,8]
assign2 = [2,3,4,5]
assign3 = [9,10]

In [15]:
newlist=[]
for i in assign1:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))

In [16]:
newlist=[]
for i in assign2:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))

In [17]:
newlist=[]
for i in assign3:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))

In [18]:
newC1

[array([-0.25,  0.5 ]), array([ 2.75,  2.  ]), array([ 0.75, -1.  ])]

In [19]:
f=open('P3_step2.txt','wb')

for i in range(len(data)):
    r=[]
    for j in range(len(C)):
        dist = float("{0:.2f}".format(math.sqrt((data[i][0]-newC1[j][0])**2+(data[i][1]-newC1[j][1])**2)))
        r.append(dist)
        f.write(str(dist)+'\t')
    f.write(str(r.index(min(r))+1))
    f.write('\n')
f.close()

In [20]:
newC1=[]
assign1 = [1,6,7,8]
assign2 = [2,3,4,5]
assign3 = [9,10]

In [21]:
newlist=[]
for i in assign1:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))
newlist=[]
for i in assign2:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))
newlist=[]
for i in assign3:
    newlist.append(data[i-1])
newC1.append(CoG(newlist))

In [22]:
newC1

[array([-0.25,  0.5 ]), array([ 2.75,  2.  ]), array([ 0.75, -1.  ])]

In [23]:
## Problem 1

In [24]:
f=open('P1_data.txt','rb')
P=[]
for line in f:
    P.append(float(line))

In [25]:
f.close()

In [30]:
g=len(P)
FDR=0.2

In [39]:
Q=[]
for i in range(g):
    Q.append((i+1)*FDR/g)

In [40]:
Q

[0.01,
 0.02,
 0.030000000000000006,
 0.04,
 0.05,
 0.06000000000000001,
 0.07,
 0.08,
 0.09,
 0.1,
 0.11000000000000001,
 0.12000000000000002,
 0.13,
 0.14,
 0.15,
 0.16,
 0.17,
 0.18,
 0.19,
 0.2]

In [42]:
for i in range(g):
    if (P[i]<=Q[i]):
        print i+1

1
2
3
4
5
6
7
8
9
10
11
12
